# Generated by Django 4.2.3 on 2023-07-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(choices=[('book', 'book'), ('article', 'article'), ('chapter', 'chapter'), ('multivolume', 'multivolume')], default='book', max_length=20)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('completion', models.CharField(blank=True, max_length=4)),
                ('volumes', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=2048)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('topics', models.CharField(choices=[('unselected', 'unselected'), ('Theory of bibliographical analysis', 'Theory of bibliographical analysis'), ('History of bibliographical analysis', 'History of bibliographical analysis')], default='book', max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
