# Generated by Django 4.2.3 on 2023-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanselle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bib',
            name='city',
        ),
        migrations.AlterField(
            model_name='bib',
            name='topics',
            field=models.CharField(choices=[('unselected', 'unselected'), ('Basic Reading', 'Basic Reading'), ('Theory of bibliographical analysis', 'Theory of bibliographical analysis'), ('History of bibliographical analysis', 'History of bibliographical analysis')], default='book', max_length=255),
        ),
    ]
