# Generated by Django 4.2.3 on 2023-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanselle', '0003_remove_bib_topics_alter_bib_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bib',
            name='anthology',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
